version: '3'

services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "9889:80"
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html
    
